package it.dcs.iscrivo.mailclientnew.dao.enums;

public enum CriteriaOperator {
	EQUALS, NOT_EQUALS, LIKE, STARTS_WITH, ENDS_WITH, IS_NOT_NULL, IS_NULL, IS_EMPTY, IS_NOT_EMPTY, IN, NOT_IN, MORE, MORE_EQUAL, LESS, LESS_EQUAL, JOIN_EQUALS, JOIN_NOT_EQUALS, JOIN_LIKE, JOIN_START_WITH, JOIN_ENDS_WITH, JOIN_IS_NOT_NULL, JOIN_IS_NULL, JOIN_IS_EMPTY, JOIN_IS_NOT_EMPTY, JOIN_IN, JOIN_NOT_IN, JOIN_MORE, JOIN_MORE_EQUAL, JOIN_LESS, JOIN_LESS_EQUAL;
}
